name: minild57
description: A sample dartemis application
dependencies:
  browser: any
  dartemis:
    path: ../dartemis
  gamedev_helpers:
#    git: https://github.com/denniskaselow/gamedev_helpers
    path: ../gamedev_helpers
  dart_to_js_script_rewriter: any
transformers:
- dart_to_js_script_rewriter
- dartemis:
    additionalLibraries:
    - gamedev_helpers/gamedev_helpers.dart
