name: minild57
description: A sample dartemis application
dependencies:
  browser: any
  gamedev_helpers:
    path: ../gamedev_helpers
  dartemis:
      git:
        url: git://github.com/denniskaselow/dartemis.git
        ref: develop
  dartemis_transformer:
    path: ../dartemis_transformer
  dart_to_js_script_rewriter: any
transformers:
- dart_to_js_script_rewriter
- dartemis_transformer:
    additionalLibraries:
    - gamedev_helpers/gamedev_helpers.dart
    - gamedev_helpers/gamedev_helpers_shared.dart
